### ISSUE TITLE
Error about LWT

### ISSUE THREAD

**Issue by znshi** [ChunmingHe/FEDER#4]
图像的尺寸是384*384，运行时出现如下错误？求指教？
Traceback (most recent call last):
  File "Train.py", line 240, in <module>
    train(train_loader, model, optimizer, epoch, save_path, writer)
  File "Train.py", line 51, in train
    preds = model(images)
  File "/home/shizenan/anaconda3/envs/FEDER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shizenan/anaconda3/envs/FEDER/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/shizenan/anaconda3/envs/FEDER/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/shizenan/anaconda3/envs/FEDER/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/shizenan/anaconda3/envs/FEDER/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/shizenan/anaconda3/envs/FEDER/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/shizenan/anaconda3/envs/FEDER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shizenan/FEDER-main/lib/Network.py", line 34, in forward
    LL, LH, HL, HH, f1, f2, f3, f4 = self.GCM3(x1, x2, x3, x4)
  File "/home/shizenan/anaconda3/envs/FEDER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shizenan/FEDER-main/lib/Modules.py", line 468, in forward
    wf2 = self.DWT(f2)
  File "/home/shizenan/anaconda3/envs/FEDER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shizenan/FEDER-main/lib/Modules.py", line 205, in forward
    ll = x1 + x2 + x3 + x4
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

**Comment by Hai-chao-Zhang** [comment]
Can I put torch.nn.functional.interpolate(tensor2, size=(5, 5), mode='bilinear', align_corners=False) on every where to fix this?

**Comment by ChunmingHe** [comment]
Yes, feel free to modify the code to accommodate your device
